Fix: cicd workflow

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -51,6 +51,10 @@ jobs:
         run: |
           sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" manifests/deployment.yaml
 
+      - name: Clean up old deployment
+        run: |
+          kubectl delete deployment my-app || echo "Deployment already deleted or not found."
+
       - name: Apply manifest to EKS
         run: |
           kubectl apply -f manifests/deployment.yaml
